# Generated by Django 3.1.6 on 2021-02-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания пользователя')),
                ('registration_date', models.DateTimeField(verbose_name='Дата регистрации пользователя')),
                ('name', models.CharField(max_length=200, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='эл. почта пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='время события')),
                ('action_id', models.IntegerField(default=0, verbose_name='идентификатор действия')),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktracker.step', verbose_name='идентификатор объекта над которым совершается действие (step_id)')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktracker.user', verbose_name='идентификатор пользователя')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
