# Generated by Django 3.1.6 on 2021-02-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='время события'),
        ),
    ]
